gb_tricks_homepage:
    path:     /{page}
    defaults: 
        _controller: GBTricksBundle:Trick:index
        page:        1
    requirements:
        page: \d+
    
gb_tricks_trickpage:
    path:     /trick/{trick_id}/{messageList}
    defaults: 
        _controller: GBTricksBundle:Trick:view
        messageList: 1
    requirements:
        trick_id: \d+
        messageList: \d+
           
gb_tricks_add:
    path:     /add
    defaults: { _controller: GBTricksBundle:Trick:add }

gb_tricks_modify:
    path:     /modify/{trick_id}
    defaults: { _controller: GBTricksBundle:Trick:modify }
    requirements:
        trick_id: \d+
        
gb_tricks_delete:
    path:     /delete/{trick_id}
    defaults: { _controller: GBTricksBundle:Trick:delete }
    requirements:
        trick_id: \d+

gb_tricks_addmessage:
    path:     /trick/{trick_id}/message
    defaults: { _ controller: GBTricksBundle:Trick:addMessage }
    requirements:
        trick_id: \d+