services:
    gb_user.validator.username:
        class: GB\UserBundle\Validator\UserNameValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: gb_user_username }
    gb_user.validator.password:
        class: GB\UserBundle\Validator\PasswordValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        autowire: true # or define your controller constructor and configure its arguments explicitly
        tags: 
        - 'controller.service_arguments'
        - { name: validator.constraint_validator, alias: gb_user_password }
        
