services:
    gb_user.validator.userexist:
        class: GB\UserBundle\Validator\UserExistValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: gb_user_userexist }
    
    gb_user.validator.registration:
        class: GB\UserBundle\Validator\RegistrationValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: gb_user_registration_validator }        
            
    gb_user.validator.password:
        class: GB\UserBundle\Validator\PasswordValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        autowire: true # or define your controller constructor and configure its arguments explicitly
        tags: 
        - 'controller.service_arguments'
        - { name: validator.constraint_validator, alias: gb_user_password }
        
